apiVersion: v1
kind: Pod
metadata:
  name: selector
  labels:
    purpose: "selector-demo"
spec:
  nodeselector:
     
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80