apiVersion: v1
kind: Pod
metadata:
  name: toleration
  labels:
    purpose: "toleration-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
     
  containers:
  - name: nginx
    image: nginx